blueprint:
  name: Camera Snapshot, AI & Notifications to Mobile Color Telegram Speakers More
  description: > 
    # 📢 Chụp ảnh, Phân tích ảnh bằng AI và gửi Thông báo nếu Cảm biến kích hoạt
    
    
    **Phiên bản: 1.0**
            
    
      1- **Thông báo phân tích hình ảnh bằng AI lên ứng dụng Home Assistant, Telegram và TTS ra Loa được tích hợp vào Home Assistant 💬🔉**
    
      2- **Có thể tùy chọn gửi thông báo lên nhiều Điện thoại, Telegram và lên nhiều Loa được tính hợp trong Home Assistant.**
      
      3- **Có thể thêm nhiều Hành động tùy chọn nếu muốn thực hiện.**
      
      4- **Có thể thêm nhiều Điều kiện để chạy Automation**
      

    <details>
    <summary><b>Tiến trình:</b> - Nhấn để mở rộng</summary>
    
    
      - **Motion sensor:**
        - Chọn cảm biến muốn kích hoạt từ danh sách cảm biến để chạy Automation.
      
      
      - **Camera:**
        - Chọn camera từ danh sách để chụp ảnh.
      
      
      - **Location save Snapshots Option (Optional):**
        - Chọn vị trí lưu ảnh chụp.
        - Thư mục **media** mặc định
        - Muốn đổi sang thư mục **www** thì chọn **WWW Folder**
      
      
      - **Mobile App Notify:** Chọn điện thoại muốn đẩy thông báo nếu muốn. Mặc định không Bật.
        - **Use The Mobile App Notify Option (Optional):** Chọn Enable Mobile App Notify Options để bật tính năng thông báo lên Điện thoại.
        - **Devices Notified:** Chọn Điện thoại muốn đẩy thông báo lên.
        - **Title:** Nhập Tiêu đề cho thông báo trên điện thoại.
    
    
      - **Telegram Notifications Settings:** Tùy chọn cho việc đẩy thông báo lên Telegram. Mặc định Tắt.
        - **Use Telegram Notifications Option (Optional):** Chọn Enable Telegram Notifications để bật tính năng thông báo lên Telegram.
        - **Telegram Group ID:** Nhập Chat ID Telegram. Nếu đẩy vào Group thì nhập Topic ID bên dưới.
        - **Telegram Topic ID:** Nhập Topic ID nếu muốn đẩy thông báo vào Topic của Group. Không sử dụng Group thì để trống.
      
      
      - **Text-to-Speech Announcement:** Bật tính năng thông báo nội dung ra Loa được tích hợp vào Home Assistant. Mặc định không Bật.
        - **Use The Text-to-Speech Announcement Option (Optional):** Chọn Enable Text-to-Speech Announcements để - **bật tính năng thông báo lên Loa.
        - **Text-to-Speech Service Provider:** Chọn Ngôn ngữ.
        - **Media Player:** Nhập Tiêu đề cho thông báo trên điện thoại.
    
    
      - **Prompt | Number | Delay of Snapshots:** Các cài đặt cho AI, Số ảnh cần chụp, Thời gian trễ sau mỗi lần chụp.
        - **Number of Snapshots:** Kéo để thiết lập Số ảnh sẽ chụp để so sánh (từ 1 đến 5).
        - **Delay after Trigger:** Kéo để thiết lập Thời gian trễ sau khi Triggers và bắt đầu Snapshots (tính theo ms).
        - **Delay after Snapshots:** Kéo để thiết lập Thời gian trễ sau mỗi lần Snapshots (tính theo ms).
        - **AI Prompt:** Câu lệnh cho AI phân tích. Bạn có thể thay đổi câu lệnh mặc định.
      
      
      - **Custom Actions:**
        - **Enable Custom Actions:** Chọn Enable Custom Actions nếu bạn muốn thêm các Hành động khác để thực hiện trong Automation.
        - **Custom Actions:** Thêm các hành động tùy chọn để thực hiện trong Automation.
    
    
      - **Global Conditions:**
        - **Add Condition(s) to run this Automation:** Thêm điều kiện để chạy Automation. Automation chỉ chạy khi Điều kiện này Đúng.
    
    
      - **Is it an iOS device?:**
        - **Is it an iOS device?:** Bật nếu thiết bị muốn thông báo Mobile App Notify chạy iOS, Mặc định là Android.
    </details>      
    
    
      
    Cần Có = <b>*</b>
    
    
  domain: automation
  input:

    motion_sensor:
      name: Motion sensor
      description: Chọn cảm biến để kích hoạt chụp ảnh.
      selector:
        entity:
          domain: binary_sensor
          device_class: 
            - motion
            - occupancy
            
    camera_device:
      name: Camera
      description: Camera mà bạn muốn chụp ảnh
      selector:
        entity:
          domain: camera
          
    image_path:
      name: Location save Snapshots Option (Optional)
      description: >
        Chọn vị trí sẽ lưu ảnh Snapshots
        Thư mục `media` hoặc `www (/local/..)` 
      default: media_folder
      selector:
        select:
          options:
            - label: Media Folder
              value: "media_folder"
            - label: WWW Folder
              value: "www_folder"
                    
    device_notify_settings:
      name: "Mobile App Notify"
      icon: mdi:devices
      collapsed: true
      input:
        include_notify:
          name: Use The Mobile App Notify Option (Optional)
          description: >
            Enable nếu muốn gửi thông báo lên điện thoại đã chọn bên dưới.
          default: disable_mobile_app_notify
          selector:
            select:
              options:
                - label: Enable Mobile App Notify Options
                  value: "enable_mobile_app_notify"
                - label: Disable Mobile App Notify Options
                  value: "disable_mobile_app_notify"
          
        is_ios_android:
          name: Is it an Android or iOS device?
          description: >
            Chọn điện thoại đẩy thông báo là Android hay iOS?
          default: android_device
          selector:
            select:
              options:
                - label: Android
                  value: "android_device"
                - label: iOS
                  value: "ios_device"
        notify_device:
          name: Devices Notified
          description: >
            Chọn Điện thoại muốn thông bảo đẩy lên.
          default: []
          selector:
            device:
              filter:
                - integration: mobile_app
              multiple: true
        notify_title:
          name: Title
          description: >
            Nhập Title của Thông báo.
            Có thẻ dùng CSS HTML để thiết lập màu sắc, In đậm,... cho nội dung
          default: >
            📢 Nhập <b><span style="color: red">Tiêu Đề</span></b><i> cho thông báo ở đây</i>{{'\n'}}|-->{{now().strftime('%H:%M:%S %a, %d-%b-%Y')}}
          selector: 
            text:
        status_bar_icon:
          name: "🌠 Status Bar Icon"
          description: >
            `Dành cho` `Android`
            Thiết lập icon cho thông báo trên Status Bar điện thoại
            Tìm icon tại https://pictogrammers.com/library/mdi/
          default: mdi:motion-sensor
          selector:
            icon:
              placeholder: mdi:motion-sensor
        notification_color:
          name: "🎨 Notification Color"
          description: >
            `Dành cho` `Android`
            Thiết lập màu cho icon thông báo trên Status Bar điện thoại
          default: [100, 200, 240]
          selector:
            color_rgb:
         
    telegram_settings:
      name: "Telegram Notifications Settings"
      icon: mdi:message-badge
      collapsed: true
      input:
        include_telegram_notify:
          name: Use Telegram Notifications Option (Optional)
          description: >
            Enable nếu muốn gửi thông báo lên Telegram.
          default: disable_telegram_notification
          selector:
            select:
              options:
                - label: Enable Telegram Notifications
                  value: "enable_telegram_notification"
                - label: Disable Telegram Notifications
                  value: "disable_telegram_notification"
        telegram_group_id:
          name: Telegram Group ID
          description: ID của nhóm Telegram (để trống nếu không dùng).
          selector:
            text:
          default: ""

        telegram_topic:
          name: Telegram Topic ID
          description: ID của chủ đề trong nhóm Telegram (để trống nếu không dùng).
          selector:
            text:
          default: ""
          
    tts_notify_settings:
      name: "Text-to-Speech Announcement"
      icon: mdi:speaker-message
      collapsed: true
      input:
        include_tts_announcement:
          name: Use The Text-to-Speech Announcement Option (Optional)
          description: >
            Enable khi muốn gửi TTS ra loa sẽ chọn bên dưới.
          default: disable_tts_announcement
          selector:
            select:
              options:
                - label: Enable Text-to-Speech Announcements
                  value: "enable_tts_announcement"
                - label: Disable Text-to-Speech Announcements
                  value: "disable_tts_announcement"
        text_to_speech_engine:
          name: Text-to-Speech Service Provider
          description: >
            Chọn dịch vụ TTS hỗ trợ.
          default: []
          selector:
            entity:
              filter:
                domain: tts
        media_player:
          name: Media Player
          description: >
            Chọn loa để phát thông báo
          default: []
          selector:
            entity:
              filter:
                domain: media_player
              multiple: true
 
    prompt_number_delay_settings:
      name: "Prompt | Number | Delay of Snapshots"
      icon: mdi:clock-start
      collapsed: true
      input:
        num_snapshots:
          name: Number of Snapshots
          description: Số ảnh sẽ chụp để so sánh (từ 1 đến 5)
          selector:
            number:
              min: 1
              max: 5
              unit_of_measurement: snapshots
          default: 3
        num_delay_actions:
          name: Delay after Trigger
          description: Thời gian trễ sau khi Triggers và bắt đầu Snapshots (tính theo ms)
          selector:
            number:
              min: 500
              max: 5000
              step: 500
              unit_of_measurement: ms
          default: 500
        num_delay:
          name: Delay after Snapshots
          description: Thời gian trễ sau mỗi lần Snapshots (tính theo ms)
          selector:
            number:
              min: 400
              max: 3000
              step: 100
              unit_of_measurement: ms
          default: 500

        ai_prompt:
          name: AI Prompt
          description: Câu lệnh cho AI phân tích.
          selector:
            text:
              multiline: true
          default: >
            Dùng ngôn ngữ Việt Nam. Hãy so sánh và mô tả rất ngắn gọn những gì bạn thấy trong chuỗi hình ảnh
            sau từ máy ảnh {{ camera_name }} của tôi. Nếu có người, động vật, xe máy
            hoặc ô tô, hãy mô tả chi tiết về chúng. Không mô tả các vật thể hoặc tòa
            nhà cố định. Nếu trong chuỗi ảnh không có người hãy trả lời "Đã phát hiện chuyển động tuy nhiên không có người trong chuỗi ảnh khi so sánh". Tin nhắn của bạn cần đủ ngắn để có thể đưa vào thông báo trên điện thoại.
        
    custom_actions_settings:
      name: "Custom Actions"
      icon: mdi:gesture-tap-button
      collapsed: true
      input:
        include_custom_actions:
          name: Use The Custom Action Options (Optional)
          description: >
            Chọn Enable Custom Actions và thêm Actions bên dưới nếu bạn muốn thêm các Hành động khác để thực hiện trong Automation này.
          default: disable_custom_actions
          selector:
            select:
              options:
                - label: Enable Custom Actions
                  value: "enable_custom_actions"
                - label: Disable Custom Actions
                  value: "disable_custom_actions"
        custom_actions:
          name: Custom Actions
          description: >
            Thêm bất kỳ hành động nào bạn muốn chạy trong Automation này.
            Biến lấy nội dung phân tích AI cho các nội dung khác: `generated_content['text']`
          default: []
          selector:
            action:

    global_conditions_settings:
      name: "Global Conditions"
      icon: mdi:earth
      collapsed: true
      input:
        global_conditions:
          name: Add Condition(s) to run this Automation
          description: >
            Thêm Condition để chạy Automation. Automation chỉ chạy khi Conditions này là True.
          default: []
          selector:
            condition:

trigger:
  platform: state
  entity_id: !input motion_sensor
  to: 'on'

variables:
  #Device Notify
  include_notify: !input include_notify
  notify_device: !input notify_device
  notify_title: !input notify_title
  filtered_devices: >
    {{ notify_device }}
  
  #Camera
  camera_device: !input camera_device
  camera_name: "{{ state_attr(camera_device, 'friendly_name') }}"
  camera_path: "{{ state_attr(camera_device, 'friendly_name') | lower | replace(' ', '_') }}"
  #Motion Sensor
  motion_sensor: !input motion_sensor
  motion_name: "{{ state_attr(motion_sensor, 'friendly_name') }}"
  #Snapshot
  image_path: !input image_path
  num_delay_actions: !input num_delay_actions
  num_snapshots: !input num_snapshots
  num_delay: !input num_delay
  #AI
  ai_prompt: !input ai_prompt
  #Telegram Message
  include_telegram_notify: !input include_telegram_notify
  telegram_group_id: !input telegram_group_id
  telegram_topic: !input telegram_topic
  #TTS Message
  include_tts_announcement: !input include_tts_announcement
  text_to_speech_engine: !input text_to_speech_engine
  media_player: !input media_player
  #Custom Actions
  include_custom_actions: !input include_custom_actions
  custom_actions: !input custom_actions
  #Global Conditions
  global_conditions: !input global_conditions
  #Iphone
  is_ios_android: !input 'is_ios_android'
  
# All Conditions
condition:
# Global Conditions
  - condition: and
    conditions: !input global_conditions

action:
  - variables:
      snapshot_access_file_path: >
        {% if image_path == 'media_folder' %}
          /media/local/snapshots/{{camera_path}}_snapshot1.jpg
        {% else %}
          /local/snapshots/{{camera_path}}_snapshot1.jpg
        {% endif %}
      snapshot_access_file_path_tele: >
        {% if image_path == 'media_folder' %}
          /media/snapshots/{{camera_path}}_snapshot1.jpg
        {% else %}
          ./www/snapshots/{{camera_path}}_snapshot1.jpg
        {% endif %}
      notification_color: !input "notification_color"
      notification_color_hex: "#{{ '%02x%02x%02x' | format(notification_color[0], notification_color[1], notification_color[2]) }}"
      
  - delay:
      milliseconds: "{{ num_delay_actions }}"
    
  - choose:
      - alias: "Media Folder"
        conditions:
          - "{{ image_path == 'media_folder' }}"
        sequence:
          - repeat:
              count: "{{ num_snapshots }}"
              sequence:
                - service: camera.snapshot
                  data:
                    filename: "/media/snapshots/{{ camera_path }}_snapshot{{ repeat.index }}.jpg"
                  target:
                    entity_id: "{{ camera_device }}"
                - delay:
                    milliseconds: "{{ num_delay }}"
      - alias: "WWW Folder"
        conditions:
          - "{{ image_path == 'www_folder' }}"
        sequence:
          - repeat:
              count: "{{ num_snapshots }}"
              sequence:
                - service: camera.snapshot
                  data:
                    filename: "./www/snapshots/{{ camera_path }}_snapshot{{ repeat.index }}.jpg"
                  target:
                    entity_id: "{{ camera_device }}"
                - delay:
                    milliseconds: "{{ num_delay }}"
  - service: google_generative_ai_conversation.generate_content
    data:
      prompt: "{{ ai_prompt }}"
      filenames: >
        {% set snap_count = num_snapshots %}
        {% set ns = namespace(images=[]) %}
        {% if image_path == 'media_folder'%}
          {% for i in range(1, snap_count + 1) %}
            {% set image = "/media/snapshots/" ~ camera_path ~ "_snapshot" ~ i ~ ".jpg" %} 
            {% set ns.images = ns.images + [image] %}
          {% endfor %}
        {% else %}
          {% for i in range(1, snap_count + 1) %}
            {% set image = "./www/snapshots/" ~ camera_path ~ "_snapshot" ~ i ~ ".jpg" %}
            {% set ns.images = ns.images + [image] %}
          {% endfor %}
        {% endif %}
        {{ ns.images }}
    response_variable: generated_content
    
  - choose:
      - alias: "Check if notification is enabled"
        conditions:
          - "{{ include_notify == 'enable_mobile_app_notify' }}"
          - "{{ filtered_devices | length > 0 }}"
        sequence:
          - choose:
            - alias: "Check if Android"
              conditions:
                - "{{ is_ios_android == 'android_device' }}"
              sequence:
              - alias: Send a notification to each device
                repeat:
                  for_each: "{{ filtered_devices }}"
                  sequence:
                    - action: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                      data:
                        title: !input notify_title
                        message: "{{ generated_content['text'] }}"
                        data:
                          priority: high
                          notification_icon: !input status_bar_icon
                          color: "{{ notification_color_hex }}"
                          image: "{{snapshot_access_file_path}}"
            - alias: "Check if iOS"
              conditions:
                - "{{ is_ios_android == 'ios_device' }}"
              sequence:
              - action: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                data:
                  title: !input notify_title
                  message: >
                    {{ generated_content['text'] }}
                  data:
                    attachment:
                      url: "{{snapshot_access_file_path}}"
                      content_type: "JPEG"
                      
  - choose:
    - alias: "Check if Telegram Notifications Option is enabled"
      conditions:
        - "{{ include_telegram_notify == 'enable_telegram_notification' }}"
      sequence:
        - service: telegram_bot.send_photo
          data:
            authentication: digest
            target: "{{ telegram_group_id }}"
            message_thread_id: "{{ telegram_topic | int(0) }}"
            file: "{{ snapshot_access_file_path_tele }}"
            caption: >
              🔍 Kết quả phân tích AI 🤖:
              {{'\n'}}|--> {{now().strftime('%H:%M:%S %a, %d-%b-%Y')}}
              {{'\n'}}{{generated_content['text']}}

  - choose:
    - alias: "Check if tts announcement is enabled"
      conditions:
        - "{{ include_tts_announcement == 'enable_tts_announcement' }}"
      sequence:
        - action: tts.speak
          target:
            entity_id: !input text_to_speech_engine
          data:
            media_player_entity_id: !input media_player
            message: "{{generated_content['text']}}"
             
  - choose:
    - alias: "Perform the custom action"
      conditions:
        - condition: template
          value_template: "{{ 'enable_custom_actions' in include_custom_actions }}"
      sequence: !input custom_actions

mode: single
max_exceeded: silent
